name = "AhoCorasick"
uuid = "c3ca9c75-fc23-4c85-84e6-d64869b4d213"
authors = ["Caleb-Chandrasekar"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
